<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Descriptive statistics | Statistics in R</title>
  <meta name="description" content="Chapter 3 Descriptive statistics | Statistics in R" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Descriptive statistics | Statistics in R" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Descriptive statistics | Statistics in R" />
  
  
  

<meta name="author" content="Pavel Logacev" />


<meta name="date" content="2020-12-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="scalesOfMeasurement.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Initial Remarks</a></li>
<li class="chapter" data-level="2" data-path="scalesOfMeasurement.html"><a href="scalesOfMeasurement.html"><i class="fa fa-check"></i><b>2</b> Scales of Measurement</a><ul>
<li class="chapter" data-level="2.1" data-path="scalesOfMeasurement.html"><a href="scalesOfMeasurement.html#nominal-scale"><i class="fa fa-check"></i><b>2.1</b> Nominal scale</a></li>
<li class="chapter" data-level="2.2" data-path="scalesOfMeasurement.html"><a href="scalesOfMeasurement.html#ordinal-scale"><i class="fa fa-check"></i><b>2.2</b> Ordinal scale</a></li>
<li class="chapter" data-level="2.3" data-path="scalesOfMeasurement.html"><a href="scalesOfMeasurement.html#interval-scale"><i class="fa fa-check"></i><b>2.3</b> Interval scale</a></li>
<li class="chapter" data-level="2.4" data-path="scalesOfMeasurement.html"><a href="scalesOfMeasurement.html#ratio-scale"><i class="fa fa-check"></i><b>2.4</b> Ratio scale</a></li>
<li class="chapter" data-level="2.5" data-path="scalesOfMeasurement.html"><a href="scalesOfMeasurement.html#continuous-versus-discrete-variables"><i class="fa fa-check"></i><b>2.5</b> Continuous versus discrete variables</a></li>
<li class="chapter" data-level="2.6" data-path="scalesOfMeasurement.html"><a href="scalesOfMeasurement.html#some-complexities"><i class="fa fa-check"></i><b>2.6</b> Some complexities</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="descriptives.html"><a href="descriptives.html"><i class="fa fa-check"></i><b>3</b> Descriptive statistics</a><ul>
<li class="chapter" data-level="3.1" data-path="descriptives.html"><a href="descriptives.html#centraltendency"><i class="fa fa-check"></i><b>3.1</b> Measures of central tendency</a><ul>
<li class="chapter" data-level="3.1.1" data-path="descriptives.html"><a href="descriptives.html#mean"><i class="fa fa-check"></i><b>3.1.1</b> The mean</a></li>
<li class="chapter" data-level="3.1.2" data-path="descriptives.html"><a href="descriptives.html#calculating-the-mean-in-r"><i class="fa fa-check"></i><b>3.1.2</b> Calculating the mean in R</a></li>
<li class="chapter" data-level="3.1.3" data-path="descriptives.html"><a href="descriptives.html#median"><i class="fa fa-check"></i><b>3.1.3</b> The median</a></li>
<li class="chapter" data-level="3.1.4" data-path="descriptives.html"><a href="descriptives.html#mean-or-median-whats-the-difference"><i class="fa fa-check"></i><b>3.1.4</b> Mean or median? What’s the difference?</a></li>
<li class="chapter" data-level="3.1.5" data-path="descriptives.html"><a href="descriptives.html#trimmedmean"><i class="fa fa-check"></i><b>3.1.5</b> Trimmed mean</a></li>
<li class="chapter" data-level="3.1.6" data-path="descriptives.html"><a href="descriptives.html#mode"><i class="fa fa-check"></i><b>3.1.6</b> Mode</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="descriptives.html"><a href="descriptives.html#summary"><i class="fa fa-check"></i><b>3.2</b> Summary</a></li>
<li class="chapter" data-level="3.3" data-path="descriptives.html"><a href="descriptives.html#var"><i class="fa fa-check"></i><b>3.3</b> Measures of variability</a><ul>
<li class="chapter" data-level="3.3.1" data-path="descriptives.html"><a href="descriptives.html#range"><i class="fa fa-check"></i><b>3.3.1</b> Range</a></li>
<li class="chapter" data-level="3.3.2" data-path="descriptives.html"><a href="descriptives.html#quantiles-and-percentile"><i class="fa fa-check"></i><b>3.3.2</b> Quantiles and percentile</a></li>
<li class="chapter" data-level="3.3.3" data-path="descriptives.html"><a href="descriptives.html#interquartile-range"><i class="fa fa-check"></i><b>3.3.3</b> Interquartile range</a></li>
<li class="chapter" data-level="3.3.4" data-path="descriptives.html"><a href="descriptives.html#aad"><i class="fa fa-check"></i><b>3.3.4</b> Mean absolute deviation</a></li>
<li class="chapter" data-level="3.3.5" data-path="descriptives.html"><a href="descriptives.html#variance"><i class="fa fa-check"></i><b>3.3.5</b> Variance</a></li>
<li class="chapter" data-level="3.3.6" data-path="descriptives.html"><a href="descriptives.html#sd"><i class="fa fa-check"></i><b>3.3.6</b> Standard deviation</a></li>
<li class="chapter" data-level="3.3.7" data-path="descriptives.html"><a href="descriptives.html#which-measure-to-use"><i class="fa fa-check"></i><b>3.3.7</b> Which measure to use?</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistics in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="descriptives" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Descriptive statistics</h1>
<p><em>(an adapted version of Danielle Navarro’s <a href="https://learningstatisticswithr.com/book/">chapter 3/5</a> on descriptive statistics.)</em></p>
<p>(07 December, 2020, 22:52)</p>
<ul>
<li><p>Any time that you get a new data set to look at, one of the first tasks that you have to do is find ways of summarising the data in a compact, easily understood fashion. This is what <strong><em>descriptive statistics</em></strong> (as opposed to <strong><em>inferential statistics</em></strong>) is all about. In fact, to many people the term “statistics” is synonymous with descriptive statistics.</p></li>
<li><p>Before going into any details, let’s take a moment to get a sense of why we need descriptive statistics. To do this, let’s load a dataset on sleep in mammals.</p></li>
</ul>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1"><span class="co">#load( &quot;./data_navarro/aflsmall.Rdata&quot; )</span></a>
<a class="sourceLine" id="cb1-2" title="2"><span class="co">#library(lsr)</span></a>
<a class="sourceLine" id="cb1-3" title="3"><span class="co">#who()</span></a>
<a class="sourceLine" id="cb1-4" title="4"></a>
<a class="sourceLine" id="cb1-5" title="5">mammalian_sleep &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb1-6" title="6"><span class="st">      </span><span class="kw">read.csv</span>(<span class="st">&quot;./data/msleep_ggplot2.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb1-7" title="7"><span class="st">      </span>dplyr<span class="op">::</span><span class="kw">select</span>(name, sleep_total, bodywt) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1-8" title="8"><span class="st">      </span>dplyr<span class="op">::</span><span class="kw">rename</span>(<span class="dt">sleep_total_h =</span> sleep_total, <span class="dt">bodywt_kg =</span> bodywt) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1-9" title="9"><span class="st">      </span>dplyr<span class="op">::</span><span class="kw">mutate</span>(<span class="dt">sleep_total_h =</span> <span class="kw">round</span>(sleep_total_h) )</a>
<a class="sourceLine" id="cb1-10" title="10"></a>
<a class="sourceLine" id="cb1-11" title="11"><span class="kw">head</span>(mammalian_sleep)</a></code></pre></div>
<pre><code>##                         name sleep_total_h bodywt_kg
## 1                    Cheetah            12    50.000
## 2                 Owl monkey            17     0.480
## 3            Mountain beaver            14     1.350
## 4 Greater short-tailed shrew            15     0.019
## 5                        Cow             4   600.000
## 6           Three-toed sloth            14     3.850</code></pre>
<!-- data: https://rstudio-pubs-static.s3.amazonaws.com/155770_0c286e39b48b4670ab7ababb103a7448.html -->
<ul>
<li><p>There are three variables here, <code>name</code>, <code>sleep_total_h</code> and <code>bodywt_kg</code>. For each animal named in <code>name</code>, the <code>sleep_total_h</code> variable contains the average number of hours animals of this kind sleep per day. The variable <code>bodywt_kg</code> contains the average weight of that animal in kg.</p></li>
<li><p>Let’s have a look at the <code>sleep_total_h</code> variable:</p></li>
</ul>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1"><span class="co">#print(afl.margins)</span></a>
<a class="sourceLine" id="cb3-2" title="2"><span class="kw">print</span>(mammalian_sleep<span class="op">$</span>sleep_total_h)</a></code></pre></div>
<pre><code>##  [1] 12 17 14 15  4 14  9  7 10  3  5  9 10 12 10  8  9 17  5 18  4 20  3  3 10
## [26] 11 15 12 10  2  3  6  6  8 10  3 19 10 14 14 13 12 20 15 11  8 14  8  4 10
## [51] 16 10 14  9 10 11 12 14  4  6 11 18  5 13  9 10  8 11 11 17 14 16 13  9  9
## [76] 16  4 16  9  5  6 12 10</code></pre>
<ul>
<li>This output doesn’t make it easy to get a sense of what the data are actually saying. Just “looking at the data” isn’t a terribly effective way of understanding data. In order to get some idea about what’s going on, we need to calculate some descriptive statistics and draw some nice pictures.
<!--
to-do: Brief explanation of histograms
(Chapter \@ref(graphics). Since the descriptive statistics are the easier of the two topics, I'll start with those, but nevertheless I'll show you a histogram of the `afl.margins` data, since it should help you get a sense of what the data we're trying to describe actually look like. But for what it's worth, this histogram -- which is shown in Figure \@ref(fig:histogram1) -- was generated using the `hist()` function. We'll talk a lot more about how to draw histograms in Section \@ref(hist). For now, it's enough to look at the histogram and note that it provides a fairly interpretable representation of the `afl.margins` data.
--></li>
<li>Let’s take a look at a <strong><em>histogram</em></strong> of these data: A <strong><em>histogram</em></strong> is a graphical representation of the frequencies of different values of ranges of values in the data.</li>
</ul>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1">  mammalian_sleep <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb5-2" title="2"><span class="st">      </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(sleep_total_h)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb5-3" title="3"><span class="st">      </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">1</span>, </a>
<a class="sourceLine" id="cb5-4" title="4">                     <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, </a>
<a class="sourceLine" id="cb5-5" title="5">                     <span class="dt">fill =</span> <span class="st">&quot;lightgrey&quot;</span>)</a></code></pre></div>
<div class="figure"><span id="fig:histogram1"></span>
<img src="LectureNotes_files/figure-html/histogram1-1.png" alt="A histogram of the average amount of sleep by animal (the `sleep_total_h` variable). As you might expect, the larger the margin the less frequently you tend to see it." width="672" />
<p class="caption">
Figure 3.1: A histogram of the average amount of sleep by animal (the <code>sleep_total_h</code> variable). As you might expect, the larger the margin the less frequently you tend to see it.
</p>
</div>
<div id="centraltendency" class="section level2">
<h2><span class="header-section-number">3.1</span> Measures of central tendency</h2>
<p>Drawing pictures of the data, as I did in Figure <a href="descriptives.html#fig:histogram1">3.1</a> is an excellent way to convey the “gist” of what the data is trying to tell you, it’s often extremely useful to try to condense the data into a few simple “summary” statistics. In most situations, the first thing that you’ll want to calculate is a measure of <strong><em>central tendency</em></strong>. That is, you’d like to know something about the “average” or “middle” of your data lies. The two most commonly used measures are the mean, median and mode; occasionally people will also report a trimmed mean. I’ll explain each of these in turn, and then discuss when each of them is useful.</p>
<div id="mean" class="section level3">
<h3><span class="header-section-number">3.1.1</span> The mean</h3>
<ul>
<li>The <strong><em>mean</em></strong> of a set of observations is just a normal, old-fashioned average: add all of the values up, and then divide by the total number of values. The first five animals’ typical amount of sleep is 12 + 17 + 14 + 15 + 4, so the mean of these observations is just:
<span class="math display">\[
\frac{12 + 17 + 14 + 15 + 4}{5} = \frac{62.4}{5} = 12.48
\]</span></li>
<li><p>Of course, this definition of the mean isn’t news to anyone: averages (i.e., means) are used so often in everyday life that this is pretty familiar stuff. However, since the concept of a mean is something that everyone already understands, I’ll use this as an excuse to start introducing some of the mathematical notation that statisticians use to describe this calculation, and talk about how the calculations would be done in R.</p></li>
<li>The first piece of notation to introduce is <span class="math inline">\(N\)</span>, which we’ll use to refer to the number of observations that we’re averaging (in this case <span class="math inline">\(N = 5\)</span>).</li>
<li>Next, we need to attach a label to the observations themselves. It’s traditional to use <span class="math inline">\(X\)</span> for this, and to use subscripts to indicate which observation we’re actually talking about.</li>
<li><p>That is, we’ll use <span class="math inline">\(X_1\)</span> to refer to the first observation, <span class="math inline">\(X_2\)</span> to refer to the second observation, and so on, all the way up to <span class="math inline">\(X_N\)</span> for the last one. Or, to say the same thing in a slightly more abstract way, we use <span class="math inline">\(X_i\)</span> to refer to the <span class="math inline">\(i\)</span>-th observation. Just to make sure we’re clear on the notation, the following table lists the 5 observations in the <code>sleep_total_h</code> variable, along with the mathematical symbol used to refer to it, and the actual value that the observation corresponds to:</p></li>
</ul>
<!-- to-do: the sleep data isn't great, because it actually consists of averages itself; moreover they are bounded -->
<table>
<thead>
<tr class="header">
<th align="left">the observation</th>
<th align="left">its symbol</th>
<th align="left">the observed value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Cheetah (animal 1)</td>
<td align="left"><span class="math inline">\(X_1\)</span></td>
<td align="left">12 hours</td>
</tr>
<tr class="even">
<td align="left">Owl monkey (animal 2)</td>
<td align="left"><span class="math inline">\(X_2\)</span></td>
<td align="left">17 hours</td>
</tr>
<tr class="odd">
<td align="left">Mountain beaver (animal 3)</td>
<td align="left"><span class="math inline">\(X_3\)</span></td>
<td align="left">14 hours</td>
</tr>
<tr class="even">
<td align="left">Greater short-tailed shrew (animal 4)</td>
<td align="left"><span class="math inline">\(X_4\)</span></td>
<td align="left">15 hours</td>
</tr>
<tr class="odd">
<td align="left">Cow (animal 5)</td>
<td align="left"><span class="math inline">\(X_5\)</span></td>
<td align="left">4 hours</td>
</tr>
</tbody>
</table>
<ul>
<li><p>Okay, now let’s try to write a formula for the mean. By tradition, we use <span class="math inline">\(\bar{X}\)</span> as the notation for the mean. So the calculation for the mean could be expressed using the following formula:
<span class="math display">\[
\bar{X} = \frac{X_1 + X_2 + ... + X_{N-1} + X_N}{N}
\]</span></p></li>
<li>This formula is entirely correct, but it’s terribly long, so we make use of the <strong><em>summation symbol</em></strong> <span class="math inline">\(\scriptstyle\sum\)</span> to shorten it.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> If I want to add up the first five observations, I could write out the sum the long way, <span class="math inline">\(X_1 + X_2 + X_3 + X_4 +X_5\)</span> or I could use the summation symbol to shorten it to this:
<span class="math display">\[
\sum_{i=1}^5 X_i
\]</span></li>
<li><p>Taken literally, this could be read as “the sum, taken over all <span class="math inline">\(i\)</span> values from 1 to 5, of the value <span class="math inline">\(X_i\)</span>”. But basically, what it means is “add up the first five observations”. In any case, we can use this notation to write out the formula for the mean, which looks like this:
<span class="math display">\[
\bar{X} = \frac{1}{N} \sum_{i=1}^N X_i 
\]</span></p></li>
<li>In all honesty, I can’t imagine that all this mathematical notation helps clarify the concept of the mean at all. In fact, it’s really just a fancy way of writing out the same thing I said in words: add all the values up, and then divide by the total number of items. However, that’s not really the reason I went into all that detail.</li>
<li>My goal was to try to make sure that everyone reading this book is clear on the notation that we’ll be using throughout the book: <span class="math inline">\(\bar{X}\)</span> for the mean, <span class="math inline">\(\scriptstyle\sum\)</span> for the idea of summation, <span class="math inline">\(X_i\)</span> for the <span class="math inline">\(i\)</span>th observation, and <span class="math inline">\(N\)</span> for the total number of observations.</li>
<li><p>We’re going to be re-using these symbols a fair bit, so it’s important that you understand them well enough to be able to “read” the equations, and to be able to see that it’s just saying “add up lots of things and then divide by another thing”.</p></li>
</ul>
</div>
<div id="calculating-the-mean-in-r" class="section level3">
<h3><span class="header-section-number">3.1.2</span> Calculating the mean in R</h3>
<p>Okay that’s the maths, how do we get the magic computing box to do the work for us? If you really wanted to, you could do this calculation directly in R. For the first numbers, do this just by typing it in as if R were a calculator…</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" title="1">(<span class="dv">12</span> <span class="op">+</span><span class="st"> </span><span class="dv">17</span> <span class="op">+</span><span class="st"> </span><span class="dv">14</span> <span class="op">+</span><span class="st"> </span><span class="dv">15</span> <span class="op">+</span><span class="st"> </span><span class="dv">4</span>) <span class="op">/</span><span class="st"> </span><span class="dv">5</span></a></code></pre></div>
<pre><code>## [1] 12.4</code></pre>
<p>… in which case R outputs the answer 36.6, just as if it were a calculator.</p>
<ul>
<li>However, we learned quicker ways of doing that</li>
</ul>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" title="1"><span class="kw">sum</span>( mammalian_sleep<span class="op">$</span>sleep_total_h[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>] )<span class="op">/</span><span class="st"> </span><span class="dv">5</span></a></code></pre></div>
<pre><code>## [1] 12.4</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" title="1"><span class="co"># or:</span></a>
<a class="sourceLine" id="cb10-2" title="2"><span class="kw">mean</span>( mammalian_sleep<span class="op">$</span>sleep_total_h[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>] )</a></code></pre></div>
<pre><code>## [1] 12.4</code></pre>
</div>
<div id="median" class="section level3">
<h3><span class="header-section-number">3.1.3</span> The median</h3>
<ul>
<li>The second measure of central tendency that people use a lot is the <strong><em>median</em></strong>, and it’s even easier to describe than the mean. The median of a set of observations is just the middle value.</li>
<li>As before let’s imagine we were interested only in the first 5 animals: They sleep 12, 17, 14, 15, and 4 hours respectively. To figure out the median, we sort these numbers into ascending order:
<span class="math display">\[
4, 12, \color{red}{14}, 15, 17
\]</span></li>
<li><p>From inspection, it’s obvious that the median value of these 5 observations is 32, since that’s the middle one in the sorted list (I’ve put it in red to make it even more obvious). Easy stuff.</p></li>
<li><p>But what should we do if we were interested in the first 6 animals rather than the first 5? Since the sixth animal sleeps for 14 hours, our sorted list is now:
<span class="math display">\[
4, 12, \color{red}{14}, \color{red}{14}, 15, 17
\]</span></p></li>
<li><p>That’s also easy. It’s still 14.</p></li>
<li>But what we do if we were interested in the first 8 animals? Here is our new sorted list.
<span class="math display">\[
4,  7,  9, \color{red}{12}, \color{red}{14}, 14, 15, 17
\]</span></li>
<li>There are now <em>two</em> middle numbers, 12 and 14. The median is defined as the average of those two numbers, which is of course 13.</li>
<li><p>To understand why, think of the median as the value that divides the sorted list of numbers into two halves – those on its left, and those on its right.</p></li>
<li><p>As before, it’s very tedious to do this by hand when you’ve got lots of numbers. To illustrate this, here’s what happens when you use R to sort all the sleep durations. First, I’ll use the <code>sort()</code> function to display the 83 numbers in increasing numerical order:</p></li>
</ul>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" title="1"><span class="kw">sort</span>( mammalian_sleep<span class="op">$</span>sleep_total_h )</a></code></pre></div>
<pre><code>##  [1]  2  3  3  3  3  3  4  4  4  4  4  5  5  5  5  6  6  6  6  7  8  8  8  8  8
## [26]  9  9  9  9  9  9  9  9 10 10 10 10 10 10 10 10 10 10 10 10 11 11 11 11 11
## [51] 11 12 12 12 12 12 12 13 13 13 14 14 14 14 14 14 14 14 15 15 15 16 16 16 16
## [76] 17 17 17 18 18 19 20 20</code></pre>
<ul>
<li>Because the vector is 83 elements long, the middle value is at position 42. This means that the median of this vector is 10. In real life, of course, no-one actually calculates the median by sorting the data and then looking for the middle value. In real life, we use the median command:</li>
</ul>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" title="1"><span class="kw">median</span>( mammalian_sleep<span class="op">$</span>sleep_total_h )</a></code></pre></div>
<pre><code>## [1] 10</code></pre>
<p>which outputs the median value of 10.</p>
</div>
<div id="mean-or-median-whats-the-difference" class="section level3">
<h3><span class="header-section-number">3.1.4</span> Mean or median? What’s the difference?</h3>
<div class="figure"><span id="fig:meanmedian"></span>
<img src="img/descriptives2/meanmedian.png" alt="An illustration of the difference between how the mean and the median should be interpreted. The mean is basically the &quot;centre of gravity&quot; of the data set: if you imagine that the histogram of the data is a solid object, then the point on which you could balance it (as if on a see-saw) is the mean. In contrast, the median is the middle observation. Half of the observations are smaller, and half of the observations are larger." width="463" />
<p class="caption">
Figure 3.2: An illustration of the difference between how the mean and the median should be interpreted. The mean is basically the “centre of gravity” of the data set: if you imagine that the histogram of the data is a solid object, then the point on which you could balance it (as if on a see-saw) is the mean. In contrast, the median is the middle observation. Half of the observations are smaller, and half of the observations are larger.
</p>
</div>
<ul>
<li>Knowing how to calculate means and medians is only a part of the story. You also need to understand what each one is saying about the data, and what that implies for when you should use each one. This is illustrated in Figure <a href="descriptives.html#fig:meanmedian">3.2</a> the mean is kind of like the “centre of gravity” of the data set, whereas the median is the “middle value” in the data. What this implies, as far as which one you should use, depends a little on what type of data you’ve got and what you’re trying to achieve. As a rough guide:</li>
</ul>
<!-- to-do: talk about scales
- If your data are nominal scale, you probably shouldn't be using either the mean or the median. Both the mean and the median rely on the idea that the numbers assigned to values are meaningful. If the numbering scheme is arbitrary, then it's probably best to use the mode (Section \@ref(mode)) instead. 
- If your data are ordinal scale, you're more likely to want to use the median than the mean. The median only makes use of the order information in your data (i.e., which numbers are bigger), but doesn't depend on the precise numbers involved. That's exactly the situation that applies when your data are ordinal scale. The mean, on the other hand, makes use of the precise numeric values assigned to the observations, so it's not really appropriate for ordinal data.
- For interval and ratio scale data, either one is generally acceptable. Which one you pick depends a bit on what you're trying to achieve. The mean has the advantage that it uses all the information in the data (which is useful when you don't have a lot of data), but it's very sensitive to extreme values, as we'll see in Section \@ref(trimmedmean).  

Let's expand on that last part a little. 
-->
<ul>
<li>One consequence is that there’s systematic differences between the mean and the median when the histogram is asymmetric (skewed; see Section <a href="#skewandkurtosis"><strong>??</strong></a>). This is illustrated in Figure <a href="descriptives.html#fig:meanmedian">3.2</a> notice that the median (right hand side) is located closer to the “body” of the histogram, whereas the mean (left hand side) gets dragged towards the “tail” (where the extreme values are).</li>
<li>To give a concrete example, suppose Bob (income $50,000), Kate (income $60,000) and Jane (income $65,000) are sitting at a table: the average income at the table is $58,333 and the median income is $60,000. Then Bill sits down with them (income $100,000,000). The average income has now jumped to $25,043,750 but the median rises only to $62,500. If you’re interested in looking at the overall income at the table, the mean might be the right answer; but if you’re interested in what counts as a typical income at the table, the median would be a better choice here.</li>
</ul>
<!--
### A real life example{#housingpriceexample}
- Income example
-->
</div>
<div id="trimmedmean" class="section level3">
<h3><span class="header-section-number">3.1.5</span> Trimmed mean</h3>
<ul>
<li>One of the fundamental rules of applied statistics is that the data are messy. Real life is never simple, and so the data sets that you obtain are never as straightforward as the statistical theory says.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> This can have awkward consequences. To illustrate, consider this rather strange looking data set (nevermind what it represents):
<span class="math display">\[
-100,2,3,4,5,6,7,8,9,10
\]</span></li>
<li>If you were to observe this in a real life data set, you’d probably suspect that something funny was going on with the <span class="math inline">\(-100\)</span> value. It’s probably an <strong><em>outlier</em></strong>, a value that doesn’t really belong with the others. You might consider removing it from the data set entirely, and in this particular case I’d probably agree with that course of action.</li>
<li>In real life, however, you don’t always get such cut-and-dried examples. For instance, you might get this instead:
<span class="math display">\[
-15,2,3,4,5,6,7,8,9,12
\]</span></li>
<li><p>The <span class="math inline">\(-15\)</span> looks a bit suspicious, but not anywhere near as much as that <span class="math inline">\(-100\)</span> did. In this case, it’s a little trickier. It <em>might</em> be a legitimate observation, it might not.</p></li>
<li><p>When faced with a situation where some of the most extreme-valued observations might not be quite trustworthy, the mean is not necessarily a good measure of central tendency. It is highly sensitive to one or two extreme values, and is thus not considered to be a <strong><em>robust</em></strong> measure.</p></li>
<li>One remedy that we’ve seen is to use the median. A more general solution is to use a “trimmed mean”. To calculate a trimmed mean, what you do is “discard” the most extreme examples on both ends (i.e., the largest and the smallest), and then take the mean of everything else. The goal is to preserve the best characteristics of the mean and the median:
<ul>
<li>just like a median, you aren’t highly influenced by extreme outliers, but …</li>
<li>like the mean, you “use” more than one of the observations.</li>
</ul></li>
<li>Generally, we describe a trimmed mean in terms of the percentage of observation on either side that are discarded. So, for instance, a 10% trimmed mean discards the largest 10% of the observations <em>and</em> the smallest 10% of the observations, and then takes the mean of the remaining 80% of the observations.</li>
<li><p>Not surprisingly, the 0% trimmed mean is just the regular mean, and the 50% trimmed mean is the median. In that sense, trimmed means provide a whole family of central tendency measures that span the range from the mean to the median.</p></li>
<li><p>For our toy example above, we have 10 observations, and so a 10% trimmed mean is calculated by ignoring the largest value (i.e., <code>12</code>) and the smallest value (i.e., <code>-15</code>) and taking the mean of the remaining values. First, let’s enter the data</p></li>
</ul>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" title="1">dataset &lt;-<span class="st"> </span><span class="kw">c</span>( <span class="dv">-15</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">9</span>,<span class="dv">12</span> )</a></code></pre></div>
<p>Next, let’s calculate means and medians:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" title="1"><span class="kw">mean</span>( dataset )</a></code></pre></div>
<pre><code>## [1] 4.1</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" title="1"><span class="kw">median</span>( dataset )</a></code></pre></div>
<pre><code>## [1] 5.5</code></pre>
<ul>
<li>That’s a fairly substantial difference, but I’m tempted to think that the mean is being influenced a bit too much by the extreme values at either end of the data set, especially the <span class="math inline">\(-15\)</span> one. So let’s just try trimming the mean a bit. If I take a 10% trimmed mean, we’ll drop the extreme values on either side, and take the mean of the rest:</li>
</ul>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" title="1"><span class="kw">mean</span>( dataset, <span class="dt">trim =</span> <span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## [1] 5.5</code></pre>
<ul>
<li>In this case it gives exactly the same answer as the median. Note that, to get a 10% trimmed mean you write <code>trim = .1</code>, not <code>trim = 10</code>.</li>
</ul>
</div>
<div id="mode" class="section level3">
<h3><span class="header-section-number">3.1.6</span> Mode</h3>
<ul>
<li>The <strong><em>mode</em></strong> is the last measure of central tendency we’ll look at. It is very simple: it is the value that occurs most frequently.</li>
<li><p>Let’s look at the some soccer data: specifically, the European Cup and Champions League results in the time from 1955-2016.</p></li>
<li><p>Lets find out which team has won the most matches. The command below tells R we just want the first 25 rows of the data.frame.</p></li>
</ul>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" title="1"><span class="kw">library</span>(engsoccerdata)</a>
<a class="sourceLine" id="cb23-2" title="2"></a>
<a class="sourceLine" id="cb23-3" title="3"><span class="kw">table</span>(champs<span class="op">$</span>tiewinner) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">sort</span>(<span class="dt">decreasing=</span>T) <span class="op">%&gt;%</span><span class="st"> </span>.[<span class="dv">1</span><span class="op">:</span><span class="dv">25</span>]</a></code></pre></div>
<pre><code>## 
##       Real Madrid     Bayern Munich        SL Benfica          AC Milan 
##               183               134               110               103 
##         Barcelona         Liverpool          Juventus       Dinamo Kiev 
##               101                97                87                82 
##            Celtic Manchester United    RSC Anderlecht          AFC Ajax 
##                81                81                75                71 
##    Internazionale  Steaua Bucuresti     Crvena Zvezda           Rangers 
##                66                63                61                58 
## Partizan Belgrade     PSV Eindhoven     Dinamo Zagreb          FC Porto 
##                52                49                48                46 
##   Atletico Madrid     Panathinaikos      BATE Borisov        CSKA Sofia 
##                45                44                40                40 
##       Galatasaray 
##                40</code></pre>
<ul>
<li>It appears that the mode of the winning team is ‘Real Madrid’. That doesn’t come as a surprise even to me.</li>
<li><p>Of course, the mode is the right (and only) summary for nominal variables.</p></li>
<li><p>But we can compute a mode for all types of variables. For example, let’s take a look at the mean, median, and mode of the total number of goals per game.</p></li>
</ul>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" title="1">champs <span class="op">%&lt;&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">total_goals =</span> hgoal <span class="op">+</span><span class="st"> </span>vgoal) <span class="co"># total goals is home team goals + visitor goals</span></a></code></pre></div>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" title="1"><span class="kw">mean</span>(champs<span class="op">$</span>total_goals)</a></code></pre></div>
<pre><code>## [1] 2.81642</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" title="1"><span class="kw">median</span>(champs<span class="op">$</span>total_goals)</a></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" title="1"><span class="kw">modeOf</span>(champs<span class="op">$</span>total_goals)</a></code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" title="1"><span class="kw">ggplot</span>(champs, <span class="kw">aes</span>(total_goals)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>()</a></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="LectureNotes_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
</div>
</div>
<div id="summary" class="section level2">
<h2><span class="header-section-number">3.2</span> Summary</h2>
<ul>
<li>There are multiple measures of central tendency that can be used to summarize an aspect of a distribution: <strong>_ (arithmetic) mean, median, and mode_</strong>.</li>
<li>They answer different questions about distribution. For example, in the distribution of number of goals per game in the previous section
<ul>
<li>mean: “If the same number of goals were scored in each game, how many goals would be scored?”</li>
<li>median: “What is a ‘mediocre’ game like?”</li>
<li>mode: “What is the most typical game like?”
<!--
mean: "If all the income were redistributed equally among the households, how much would each household make?"
median: "What is the income of the middle household?"
mode: "If we choose a household at random, what is its income most likely to be?"
trimmed mean: "What is the mean income of those who have work? (i.e., how much *can* one expect to earn *if* one finds a job)"
--></li>
</ul></li>
</ul>
</div>
<div id="var" class="section level2">
<h2><span class="header-section-number">3.3</span> Measures of variability</h2>
<ul>
<li>The statistics that we’ve discussed so far all relate to <em>central tendency</em>. That is, they all talk about which values are “in the middle” or “popular” in the data.</li>
<li>The second thing that we really want is a measure of the <strong><em>variability</em></strong> of the data.
<ul>
<li>That is, how “spread out” are the data?</li>
<li>In other words, how ‘representative’ is our measure of central tendency of most data points.</li>
</ul></li>
<li>Let’s consider interval and ratio scale data.</li>
</ul>
<div id="range" class="section level3">
<h3><span class="header-section-number">3.3.1</span> Range</h3>
<ul>
<li>The <strong><em>range</em></strong> of a variable is very simple: it’s the biggest value minus the smallest value. For the sleep data, the maximum value is 20, and the minimum value is 2. We can calculate these values in R using the <code>max()</code> and <code>min()</code> functions:</li>
</ul>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" title="1"><span class="kw">max</span>( mammalian_sleep<span class="op">$</span>sleep_total_h )</a></code></pre></div>
<pre><code>## [1] 20</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" title="1"><span class="kw">min</span>( mammalian_sleep<span class="op">$</span>sleep_total_h )</a></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>where I’ve omitted the output because it’s not interesting.</p>
<ul>
<li>The other possibility is to use the <code>range()</code> function; which outputs both the minimum value and the maximum value in a vector, like this:</li>
</ul>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" title="1"><span class="kw">range</span>( mammalian_sleep<span class="op">$</span>sleep_total_h )</a></code></pre></div>
<pre><code>## [1]  2 20</code></pre>
<ul>
<li>Although the range is the simplest way to quantify the notion of “variability”, it’s one of the worst. Recall from our discussion of the mean that we want our summary measure to be robust. If the data set has one or two extremely bad values in it, we’d like our statistics not to be unduly influenced by these cases. If we look once again at our toy example of a data set containing very extreme outliers…
<span class="math display">\[
-100,2,3,4,5,6,7,8,9,10
\]</span>
… it is clear that the range is not robust, since this has a range of 110, but if the outlier were removed we would have a range of only 8.</li>
</ul>
</div>
<div id="quantiles-and-percentile" class="section level3">
<h3><span class="header-section-number">3.3.2</span> Quantiles and percentile</h3>
<ul>
<li>A key concept we will need to build on to conceptualize several other measures of variability are <strong><em>quantiles</em></strong> or <strong><em>percentiles</em></strong>.</li>
<li>A <strong><em>percentile</em></strong> is the smallest value in a dataset such that a set percentage is smaller than it. (A <strong><em>quantile</em></strong> does pretty much the same but is more generic.)</li>
<li><p>For example, if the 10-th percentile (i.e., the <span class="math inline">\(0.1\)</span> quantile) of a list of values is 73, this means that 10 percent of the values are smaller than or equal to 73.</p></li>
<li><p>Let’s take a look at the 20 shortest sorted sleep durations and determine the 10-th percentile (<span class="math inline">\(0.1\)</span> quantile), 30-th percentile (<span class="math inline">\(0.3\)</span> quantile), 50-th percentile (<span class="math inline">\(0.5\)</span> quantile), and the 90-th percentile (<span class="math inline">\(0.9\)</span> quantile).</p></li>
<li><p>Here are the values:</p></li>
</ul>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" title="1"><span class="kw">sort</span>(mammalian_sleep<span class="op">$</span>sleep_total_h)[<span class="dv">1</span><span class="op">:</span><span class="dv">20</span>]</a></code></pre></div>
<pre><code>##  [1] 2 3 3 3 3 3 4 4 4 4 4 5 5 5 5 6 6 6 6 7</code></pre>
<ul>
<li>And here is a sorted plot:</li>
</ul>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" title="1">quantile &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.1</span>,<span class="fl">0.3</span>,<span class="fl">0.5</span>,<span class="fl">0.9</span>)</a>
<a class="sourceLine" id="cb42-2" title="2">quantile_points &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.1</span>,<span class="fl">0.3</span>,<span class="fl">0.5</span>,<span class="fl">0.9</span>)<span class="op">*</span><span class="dv">20</span></a>
<a class="sourceLine" id="cb42-3" title="3">quantile_labels &lt;-<span class="st"> </span><span class="kw">sprintf</span>(<span class="st">&quot;%0.1f quantile</span><span class="ch">\n</span><span class="st">(point %d of 20)&quot;</span>, quantile, quantile_points)</a>
<a class="sourceLine" id="cb42-4" title="4"><span class="kw">ggplot</span>(<span class="dt">data=</span><span class="ot">NULL</span>, <span class="kw">aes</span>(<span class="dt">x=</span><span class="dv">1</span><span class="op">:</span><span class="dv">20</span>, <span class="dt">y=</span><span class="kw">sort</span>(mammalian_sleep<span class="op">$</span>sleep_total_h)[<span class="dv">1</span><span class="op">:</span><span class="dv">20</span>])) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb42-5" title="5"><span class="st">    </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb42-6" title="6"><span class="st">    </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> quantile_points) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb42-7" title="7"><span class="st">    </span><span class="kw">geom_label</span>(<span class="kw">aes</span>(<span class="dt">x=</span>quantile_points, <span class="dt">y=</span><span class="fl">6.5</span>, <span class="dt">label=</span>quantile_labels ))</a></code></pre></div>
<p><img src="LectureNotes_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<ul>
<li>As you can see:
<ul>
<li>10-th percentile (<span class="math inline">\(0.1\)</span> quantile): 3</li>
<li>30-th percentile (<span class="math inline">\(0.3\)</span> quantile): 3</li>
<li>50-th percentile (<span class="math inline">\(0.5\)</span> quantile): 4</li>
<li>90-th percentile (<span class="math inline">\(0.9\)</span> quantile): 6</li>
</ul></li>
<li>The 50-th percentile is the median.</li>
</ul>
</div>
<div id="interquartile-range" class="section level3">
<h3><span class="header-section-number">3.3.3</span> Interquartile range</h3>
<ul>
<li>The <strong><em>interquartile range</em></strong> (IQR) is like the range, but instead of calculating the difference between the biggest and smallest value, it calculates the difference between the 25th quantile and the 75th quantile.</li>
<li>R provides you with a way of calculating quantiles, using the (surprise, surprise) <code>quantile()</code> function. Let’s use it to calculate the median sleep durations:</li>
</ul>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" title="1"><span class="kw">quantile</span>( <span class="dt">x =</span> mammalian_sleep<span class="op">$</span>sleep_total_h, <span class="dt">probs =</span> <span class="fl">.5</span>)</a></code></pre></div>
<pre><code>## 50% 
##  10</code></pre>
<ul>
<li>And not surprisingly, this agrees with the answer that we saw earlier with the <code>median()</code> function. Now, we can actually input lots of quantiles at once, by specifying a vector for the <code>probs</code> argument. So lets do that, and get the 25th and 75th percentile:</li>
</ul>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" title="1"><span class="kw">quantile</span>( <span class="dt">x =</span> mammalian_sleep<span class="op">$</span>sleep_total_h, <span class="dt">probs =</span> <span class="kw">c</span>(.<span class="dv">25</span>,.<span class="dv">75</span>) )</a></code></pre></div>
<pre><code>## 25% 75% 
##   8  14</code></pre>
<ul>
<li>And, by noting that <span class="math inline">\(14 - 8 = 6\)</span>, we can see that the interquartile range for the sleep durations is 6. Of course, that seems like too much work to do all that typing, so R has a built in function called <code>IQR()</code> that we can use:</li>
</ul>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" title="1"><span class="kw">IQR</span>( <span class="dt">x =</span> mammalian_sleep<span class="op">$</span>sleep_total_h )</a></code></pre></div>
<pre><code>## [1] 6</code></pre>
<ul>
<li>While it’s obvious how to interpret the range, it’s a little less obvious how to interpret the IQR. The simplest way to think about it is like this: the interquartile range is the range spanned by the “middle half” of the data. That is, one quarter of the data falls below the 25th percentile, one quarter of the data is above the 75th percentile, leaving the “middle half” of the data lying in between the two. And the IQR is the range covered by that middle half.</li>
</ul>
</div>
<div id="aad" class="section level3">
<h3><span class="header-section-number">3.3.4</span> Mean absolute deviation</h3>
<ul>
<li>The range and the interquartile range, both rely on the idea that we can measure the spread of the data by looking at the quantiles of the data.</li>
<li><p>However, this isn’t the only way to think about the problem. A different approach is to select a meaningful reference point (usually the mean or the median) and then report the <strong><em>“typical” deviations</em></strong> from that reference point.
<!--
- What do we mean by "typical" deviation? Usually, the mean or median value of these deviations! In practice, this leads to two different measures, the "mean absolute deviation (from the mean)" and the "median absolute deviation (from the median)". From what I've read, the measure based on the median seems to be used in statistics, and does seem to be the better of the two, but to be honest I don't think I've seen it used much in psychology. The measure based on the mean does occasionally show up in psychology though. In this section I'll talk about the first one, and I'll come back to talk about the second one later.
--></p></li>
<li><p>Let’s go through the <strong><em>mean absolute deviation</em></strong> (AAD for average absolute deviation, since MAD is reserved for the median absolute deviation) from the mean a little more slowly. One useful thing about this measure is that the name actually tells you exactly how to calculate it:
<span class="math display">\[
AAD(X) = \frac{1}{N} \sum_{i = 1}^N |X_i - \bar{X}|
\]</span></p></li>
<li>Let’s compute the AAD for the first data points in the sleep data:
<span class="math display">\[
12, 17, 14, 15, 4
\]</span></li>
<li>The mean of the dataset is 12.4. That is, <span class="math inline">\(\bar{X} = 12.4\)</span></li>
<li>The deviations <span class="math inline">\(X_i - \bar{X}\)</span> are:
<span class="math display">\[
-0.4, 4.6, 1.6, 2.6, -8.4
\]</span></li>
<li>The absolute deviations <span class="math inline">\(|X_i - \bar{X}|\)</span> are:
<span class="math display">\[
0.4, 4.6, 1.6, 2.6, 8.4
\]</span></li>
<li><p>The sum of the absolute deviations <span class="math inline">\(\sum_{i = 1}^N |X_i - \bar{X}|\)</span> is 17.6.
<span class="math display">\[
0.4, 4.6, 1.6, 2.6, 8.4
\]</span></p></li>
<li><p>And <span class="math inline">\(N=5\)</span>, which means, that <span class="math inline">\(AAD(X) = \frac{1}{N} \sum_{i = 1}^N |X_i - \bar{X}| = 3.52\)</span>, in our case.</p></li>
<li><p>In R, we can compute it for the entire vector.</p></li>
</ul>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" title="1">mean_sleep &lt;-<span class="st"> </span><span class="kw">mean</span>(mammalian_sleep<span class="op">$</span>sleep_total_h)</a>
<a class="sourceLine" id="cb49-2" title="2">dev_sleep &lt;-<span class="st"> </span>mean_sleep <span class="op">-</span><span class="st"> </span>mammalian_sleep<span class="op">$</span>sleep_total_h</a>
<a class="sourceLine" id="cb49-3" title="3"><span class="kw">mean</span>( <span class="kw">abs</span>(dev_sleep) )</a></code></pre></div>
<pre><code>## [1] 3.576717</code></pre>
<ul>
<li>The interpretation of the AAD is quite straightforward: It is the average distance from the average. When it’s big, the values are quite spread out. When it’s small, they are close. The units are the same (hours in our case).</li>
</ul>
<!--
and once again we'll start by pretending that there's only 5 games in total, with winning margins of 56, 31, 56, 8 and 32. Since our calculations rely on an examination of the deviation from some reference point (in this case the mean), the first thing we need to calculate is the mean, $\bar{X}$. For these five observations, our mean is $\bar{X} = 36.6$. The next step is to convert each of our observations $X_i$ into a deviation score. 

We do this by calculating the difference between the observation $X_i$ and the mean $\bar{X}$. That is, the deviation score is defined to be $X_i - \bar{X}$. For the first observation in our sample, this is equal to $56 - 36.6 = 19.4$. Okay, that's simple enough. The next step in the process is to convert these deviations to absolute deviations. As we discussed earlier when talking about  the `abs()` function in R (Section \@ref(usingfunctions)), we do this by converting any negative values to positive ones. Mathematically, we would denote the absolute value of $-3$ as $|-3|$, and so we say that $|-3| = 3$. We use the absolute value function here because we don't really care whether the value is higher than the mean or lower than the mean, we're just interested in how *close* it is to the mean. To help make this process as obvious as possible, the table below shows these calculations for all five observations:




|the observation        |its symbol |the observed value |
|:----------------------|:----------|:------------------|
|winning margin, game 1 |$X_1$      |56 points          |
|winning margin, game 2 |$X_2$      |31 points          |
|winning margin, game 3 |$X_3$      |56 points          |
|winning margin, game 4 |$X_4$      |8 points           |
|winning margin, game 5 |$X_5$      |32 points          |

Now that we have calculated the absolute deviation score for every observation in the data set, all that we have to do to calculate the mean of these scores. Let's do that:
$$
\frac{19.4 + 5.6 + 19.4 + 28.6 + 4.6}{5} = 15.52
$$
And we're done. The mean absolute deviation for these five scores is 15.52. 

However, while our calculations for this little example are at an end, we do have a couple of things left to talk about. Firstly, we should really try to write down a proper mathematical formula. But in order do to this I need some mathematical notation to refer to the mean absolute deviation. Irritatingly, "mean absolute deviation" and "median absolute deviation" have the same acronym (MAD), which leads to a certain amount of ambiguity, and since R tends to use MAD to refer to the median absolute deviation, I'd better come up with something different for the mean absolute deviation. Sigh. What I'll do is use AAD instead, short for *average* absolute deviation. Now that we have some unambiguous notation, here's the formula that describes what we just calculated:
$$
\mbox{}(X) = \frac{1}{N} \sum_{i = 1}^N |X_i - \bar{X}|
$$

The last thing we need to talk about is how to calculate AAD in R. One possibility would be to do everything using low level commands, laboriously following the same steps that I used when describing the calculations above. However, that's pretty tedious. You'd end up with a series of commands that might look like this:

```r
X <- c(56, 31,56,8,32)   # enter the data
X.bar <- mean( X )       # step 1. the mean of the data
AD <- abs( X - X.bar )   # step 2. the absolute deviations from the mean
AAD <- mean( AD )        # step 3. the mean absolute deviations
print( AAD )             # print the results
```

```
## [1] 15.52
```

Each of those commands is pretty simple, but there's just too many of them. And because I find that to be too much typing, the `lsr` package has a very simple function called `aad()` that does the calculations for you. If we apply the `aad()` function to our data, we get this:

```r
library(lsr)
aad( X )
```

```
## [1] 15.52
```
No suprises there.
-->
</div>
<div id="variance" class="section level3">
<h3><span class="header-section-number">3.3.5</span> Variance</h3>
<ul>
<li>Although the mean absolute deviation measure has its uses, it’s not the best measure of variability to use.</li>
<li>From a purely mathematical perspective, there are some solid reasons to prefer squared deviations rather than absolute deviations.</li>
<li>If we do that, we obtain a measure is called the <strong><em>variance</em></strong>, which has a lot of really nice statistical properties that I’m going to ignore,<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a>(X)$ and <span class="math inline">\(\mbox{Var}(Y)\)</span> respectively. Now imagine I want to define a new variable <span class="math inline">\(Z\)</span> that is the sum of the two, <span class="math inline">\(Z = X+Y\)</span>. As it turns out, the variance of <span class="math inline">\(Z\)</span> is equal to <span class="math inline">\(\mbox{Var}(X) + \mbox{Var}(Y)\)</span>. This is a <em>very</em> useful property, but it’s not true of the other measures that I talk about in this section.] and one massive psychological flaw that I’m going to make a big deal out of in a moment. The variance of a data set <span class="math inline">\(X\)</span> is sometimes written as <span class="math inline">\(\mbox{Var}(X)\)</span>, but it’s more commonly denoted <span class="math inline">\(s^2\)</span> (the reason for this will become clearer shortly). The formula that we use to calculate the variance of a set of observations is as follows:
<span class="math display">\[
\mbox{Var}(X) = \frac{1}{N} \sum_{i=1}^N \left( X_i - \bar{X} \right)^2
\]</span>
<span class="math display">\[\mbox{Var}(X) = \frac{\sum_{i=1}^N \left( X_i - \bar{X} \right)^2}{N}\]</span></li>
<li>As you can see, it’s basically the same formula that we used to calculate the mean absolute deviation, except that instead of using “absolute deviations” we use “squared deviations”. It is for this reason that the variance is sometimes referred to as the “mean square deviation”.</li>
</ul>
<p>Now that we’ve got the basic idea, let’s have a look at a concrete example. Once again, let’s use the first five AFL games as our data. If we follow the same approach that we took last time, we end up with the following table:</p>
<table>
<caption><span id="tab:unnamed-chunk-35">Table 3.1: </span>Regular, abssolute, and squared deviations</caption>
<colgroup>
<col width="10%" />
<col width="7%" />
<col width="7%" />
<col width="20%" />
<col width="32%" />
<col width="22%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Notation [English]</th>
<th align="left"><span class="math inline">\(i\)</span> [animal]</th>
<th align="left"><span class="math inline">\(X_i\)</span> [value]</th>
<th align="left"><span class="math inline">\(X_i - \bar{X}\)</span> [deviation from mean]</th>
<th align="left"><span class="math inline">\(&amp;#124;X_i - \bar{X}&amp;#124;\)</span> [absolute deviation from mean]</th>
<th align="left"><span class="math inline">\((X_i - \bar{X})^2\)</span> [absolute deviation]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"></td>
<td align="left">1</td>
<td align="left">12</td>
<td align="left">-0.4</td>
<td align="left">0.4</td>
<td align="left">0.16</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">2</td>
<td align="left">17</td>
<td align="left">4.6</td>
<td align="left">4.6</td>
<td align="left">21.16</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">3</td>
<td align="left">14</td>
<td align="left">1.6</td>
<td align="left">1.6</td>
<td align="left">2.56</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">4</td>
<td align="left">15</td>
<td align="left">2.6</td>
<td align="left">2.6</td>
<td align="left">6.76</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">5</td>
<td align="left">4</td>
<td align="left">-8.4</td>
<td align="left">8.4</td>
<td align="left">70.56</td>
</tr>
</tbody>
</table>
<ul>
<li>That last column contains all of our squared deviations, so all we have to do is average them. If we do that by typing all the numbers into R by hand…</li>
</ul>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" title="1">( <span class="fl">0.16+21.16+2.56+6.76+70.56</span> ) <span class="op">/</span><span class="st"> </span><span class="dv">5</span></a></code></pre></div>
<pre><code>## [1] 20.24</code></pre>
<p>… we end up with a variance of 20.24. Exciting, isn’t it? For the moment, let’s ignore the burning question that you’re all probably thinking (i.e., what the heck does a variance of 20.24 actually mean?) and instead talk a bit more about how to do the calculations in R, because this will reveal something very weird.</p>
<ul>
<li>As always, we want to avoid having to type in a whole lot of numbers ourselves. And as it happens, we have the vector <code>X</code> lying around, which we created in the previous section. With this in mind, we can calculate the variance of <code>X</code> by using the following command,</li>
</ul>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" title="1">X &lt;-<span class="st"> </span>mammalian_sleep<span class="op">$</span>sleep_total_h[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>]</a>
<a class="sourceLine" id="cb53-2" title="2"><span class="kw">mean</span>( (X <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(X) )<span class="op">^</span><span class="dv">2</span>)</a></code></pre></div>
<pre><code>## [1] 20.24</code></pre>
<p>and as usual we get the same answer as the one that we got when we did everything by hand. However, I <em>still</em> think that this is too much typing. Fortunately, R has a built in function called <code>var()</code> which does calculate variances. So we could also do this…</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" title="1"><span class="kw">var</span>(X)</a></code></pre></div>
<pre><code>## [1] 25.3</code></pre>
<p>and you get the same… no, wait… you get a completely <em>different</em> answer. That’s just weird. Is R broken?</p>
<ul>
<li>As it happens, the answer is no. It’s not a typo, and R is not making a mistake. To get a feel for what’s happening, let’s stop using the tiny data set containing only 5 data points, and switch to the full set of data points we’ve got stored in our <code>mammalian_sleep$sleep_total_h</code> vector. First, let’s calculate the variance by using the formula that I described above:</li>
</ul>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" title="1">X &lt;-<span class="st"> </span>mammalian_sleep<span class="op">$</span>sleep_total_h</a>
<a class="sourceLine" id="cb57-2" title="2"><span class="kw">mean</span>( (X <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(X) )<span class="op">^</span><span class="dv">2</span>)</a></code></pre></div>
<pre><code>## [1] 19.71171</code></pre>
<p>Now let’s use the <code>var()</code> function:</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" title="1"><span class="kw">var</span>( X )</a></code></pre></div>
<pre><code>## [1] 19.9521</code></pre>
<ul>
<li>Hm. These two numbers are very similar this time. That seems like too much of a coincidence to be a mistake. And of course it isn’t a mistake. In fact, it’s very simple to explain what R is doing here, but slightly trickier to explain <em>why</em> R is doing it. So let’s start with the “what”. What R is doing is evaluating a slightly different formula to the one I showed you above. Instead of averaging the squared deviations, which requires you to divide by the number of data points <span class="math inline">\(N\)</span>, R has chosen to divide by <span class="math inline">\(N-1\)</span>. In other words, the formula that R is using is this one<br />
<span class="math display">\[
\frac{1}{N-1} \sum_{i=1}^N \left( X_i - \bar{X} \right)^2
\]</span>
It’s easy enough to verify that this is what’s happening, as the following command illustrates:</li>
</ul>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" title="1">X &lt;-<span class="st"> </span>mammalian_sleep<span class="op">$</span>sleep_total_h[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>]</a>
<a class="sourceLine" id="cb61-2" title="2"><span class="kw">sum</span>( (X<span class="op">-</span><span class="kw">mean</span>(X))<span class="op">^</span><span class="dv">2</span> ) <span class="op">/</span><span class="st"> </span><span class="dv">4</span></a></code></pre></div>
<pre><code>## [1] 25.3</code></pre>
<ul>
<li>This is the same answer that R gave us originally when we calculated <code>var(X)</code> originally. So that’s the <em>what</em>.</li>
<li>The real question is <em>why</em> R is dividing by <span class="math inline">\(N-1\)</span> and not by <span class="math inline">\(N\)</span>. After all, the variance is supposed to be the <em>mean</em> squared deviation, right? So shouldn’t we be dividing by <span class="math inline">\(N\)</span>, the actual number of observations in the sample? Well, yes, we should. However, there’s a subtle distinction between “describing a sample” and “making guesses about the population from which the sample came”. Up to this point, it’s been a distinction without a difference. Regardless of whether you’re describing a sample or drawing inferences about the population, the mean is calculated exactly the same way. Not so for the variance, or the standard deviation, or for many other measures besides. What I outlined to you initially (i.e., take the actual average, and thus divide by <span class="math inline">\(N\)</span>) assumes that you literally intend to calculate the variance of the sample. Most of the time, however, you’re not terribly interested in the sample <em>in and of itself</em>. Rather, the sample exists to tell you something about the world. If so, you’re actually starting to move away from calculating a “sample statistic”, and towards the idea of estimating a “population parameter”.</li>
</ul>
<!--
Okay, one last thing. This section so far has read a bit like a mystery novel. I've shown you how to calculate the variance, described the weird "$N-1$" thing that R does and hinted at the reason why it's there, but I haven't mentioned the single most important thing... how do you *interpret* the variance? Descriptive statistics are supposed to describe things, after all, and right now the variance is really just a gibberish number. Unfortunately, the reason why I haven't given you the human-friendly interpretation of the variance is that there really isn't one. This is the most serious problem with the variance. Although it has some elegant mathematical properties that suggest that it really is a fundamental quantity for expressing variation, it's completely useless if you want to communicate with an actual human... variances are completely uninterpretable in terms of the original variable! All the numbers have been squared, and they don't mean anything anymore. This is a huge issue. For instance, according to the table I presented earlier, the margin in game 1 was "376.36 points-squared higher than the average margin". This is *exactly* as stupid as it sounds; and so when we calculate a variance of 324.64, we're in the same situation. I've watched a lot of footy games, and never has anyone referred to "points squared". It's *not* a real unit of measurement, and since the variance is expressed in terms of this gibberish unit, it is totally meaningless to a human.
-->
</div>
<div id="sd" class="section level3">
<h3><span class="header-section-number">3.3.6</span> Standard deviation</h3>
<ul>
<li>One problem with the variance is that it is expressed in odd units. In the case above it’s <span class="math inline">\(h^2\)</span> (<em>hours squared</em>). I know what <span class="math inline">\(m^2\)</span>, but what are <span class="math inline">\(h^2\)</span>? No idea.</li>
<li>Suppose that you’d like to have a measure that is expressed in the same units as the data itself (i.e., points, not points-squared). What should you do?</li>
<li>The solution to the problem is obvious: take the square root of the variance, known as the <strong><em>standard deviation</em></strong>, also called the “root mean squared deviation”, or RMSD. This solves out problem fairly neatly.</li>
<li>While nobody has a clue what <em>“a variance of 19.95 hours-squared”</em> really means, it’s much easier to understand <em>“a standard deviation of 4.5 hours”</em>, since it’s expressed in the original units.</li>
<li>It is traditional to refer to the standard deviation of a sample of data as <span class="math inline">\(s\)</span>, though “sd” and “std dev.” are also used at times. Because the standard deviation is equal to the square root of the variance, you probably won’t be surprised to see that the formula is:
<span class="math display">\[
s = \sqrt{ \frac{1}{N} \sum_{i=1}^N \left( X_i - \bar{X} \right)^2 }
\]</span>
and the R function that we use to calculate it is <code>sd()</code>. However, as you might have guessed from our discussion of the variance, what R actually calculates is slightly different to the formula given above. Just like the we saw with the variance, what R calculates is a version that divides by <span class="math inline">\(N-1\)</span> rather than <span class="math inline">\(N\)</span>.
<!--
For reasons that will make sense when we return to this topic in Chapter@refch:estimation I'll refer to this new quantity as $\hat\sigma$ (read as: "sigma hat"), and the formula for this is
-->
<span class="math display">\[
\hat\sigma = \sqrt{ \frac{1}{N-1} \sum_{i=1}^N \left( X_i - \bar{X} \right)^2 }
\]</span>
With that in mind, calculating standard deviations in R is simple:</li>
</ul>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb63-1" title="1"><span class="kw">sd</span>( mammalian_sleep<span class="op">$</span>sleep_total_h ) </a></code></pre></div>
<pre><code>## [1] 4.466777</code></pre>
<ul>
<li>Interpreting standard deviations is slightly more complex. Because the standard deviation is derived from the variance, and the variance is a quantity that has little to no meaning that makes sense to us humans, the standard deviation doesn’t have a simple interpretation.</li>
<li>As a consequence, most of us just rely on a simple rule of thumb: in general, you should expect 68% of the data to fall within 1 standard deviation of the mean, 95% of the data to fall within 2 standard deviation of the mean, and 99.7% of the data to fall within 3 standard deviations of the mean. This rule tends to work pretty well most of the time, but it’s not exact: it’s actually calculated based on an <em>assumption</em> that the histogram is symmetric and “bell shaped”. (Strictly, the assumption is that the data are <em>normally</em> distributed, which is an important concept that we’ll discuss more later).</li>
</ul>
<pre><code>## [1] 0.6385542</code></pre>
<!--
### Median absolute deviation{#mad}

The last measure of variability that I want to talk about is the **_median absolute deviation_** (MAD). The basic idea behind MAD is very simple, and is pretty much identical to the idea behind the mean absolute deviation (Section \@ref(aad)). The difference is that you use the median everywhere. If we were to frame this idea as a pair of R commands, they would look like this:


```r
# mean absolute deviation from the mean:
#mean( abs(afl.margins - mean(afl.margins)) )


# *median* absolute deviation from the *median*:
#median( abs(afl.margins - median(afl.margins)) )
```
This has a straightforward interpretation: every observation in the data set lies some distance away from the typical value (the median). So the MAD is an attempt to describe a *typical deviation from a typical value* in the data set. It wouldn't be unreasonable to interpret the MAD value of 19.5 for our AFL data by saying something like this:

>The median winning margin in 2010 was 30.5, indicating that a typical game involved a winning margin of about 30 points. However, there was a fair amount of variation from game to game: the MAD value was 19.5, indicating that a typical winning margin would differ from this median value by about 19-20 points.

As you'd expect, R has a built in function for calculating MAD, and you will be shocked no doubt to hear that it's called `mad()`. However, it's a little bit more complicated than the functions that we've been using previously. If you want to use it to calculate MAD in the exact same way that I have described it above, the command that you need to use specifies two arguments: the data set itself `x`, and a `constant` that I'll explain in a moment. For our purposes, the constant is 1, so our command becomes

```r
#mad( x = afl.margins, constant = 1 )
```
Apart from the weirdness of having to type that `constant = 1` part, this is pretty straightforward.

Okay, so what exactly is this `constant = 1` argument? I won't go into all the details here, but here's the gist. Although the "raw" MAD value that I've described above is completely interpretable on its own terms, that's not actually how it's used in a lot of real world contexts. Instead, what happens a lot is that the researcher *actually* wants to calculate the standard deviation. However, in the same way that the mean is very sensitive to extreme values, the standard deviation is vulnerable to the exact same issue. So, in much the same way that people sometimes use the median as a "robust" way of calculating "something that is like the mean", it's not uncommon to use MAD as a method for calculating "something that is like the standard deviation". Unfortunately, the *raw* MAD value doesn't do this. Our raw MAD value is 19.5, and our standard deviation was 26.07. However, what some clever person has shown is that, under certain assumptions^[The assumption again being that the data are normally-distributed!], you can multiply the raw MAD value by 1.4826 and obtain a number that is directly comparable to the standard deviation. As a consequence, the default value of `constant` is 1.4826, and so when you use the `mad()` command without manually setting a value, here's what you get:

```r
#mad( afl.margins )
```
I should point out, though, that if you want to use this "corrected" MAD value as a robust version of the standard deviation, you really are relying on the assumption that the data are (or at least, are "supposed to be" in some sense) symmetric and basically shaped like a bell curve. That's really *not* true for our `afl.margins` data, so in this case I wouldn't try to use the MAD value this way.
-->
</div>
<div id="which-measure-to-use" class="section level3">
<h3><span class="header-section-number">3.3.7</span> Which measure to use?</h3>
<p>We’ve discussed quite a few measures of spread (range, IQR, AAD, variance and standard deviation), and hinted at their strengths and weaknesses. Here’s a quick summary:</p>
<ul>
<li><em>Range</em>. Gives you the full spread of the data. It’s very vulnerable to outliers, and as a consequence it isn’t often used unless you have good reasons to care about the extremes in the data.</li>
<li><em>Interquartile range</em>. Tells you where the “middle half” of the data sits. It’s pretty robust, and complements the median nicely. This is used a lot.</li>
<li><em>Mean absolute deviation</em>. Tells you how far “on average” the observations are from the mean. It’s very interpretable, but has a few minor issues (not discussed here) that make it less attractive to statisticians than the standard deviation. Used sometimes, but not often.</li>
<li><em>Variance</em>. Tells you the average squared deviation from the mean. It’s mathematically elegant, and is probably the “right” way to describe variation around the mean, but it’s completely uninterpretable because it doesn’t use the same units as the data. Almost never used except as a mathematical tool; but it’s buried “under the hood” of a very large number of statistical tools.</li>
<li><em>Standard deviation</em>. This is the square root of the variance. It’s fairly elegant mathematically, and it’s expressed in the same units as the data so it can be interpreted pretty well. In situations where the mean is the measure of central tendency, this is the default. This is by far the most popular measure of variation.
<!--
- *Median absolute deviation*. The typical (i.e., median) deviation from the median value. In the raw form it's simple and interpretable; in the corrected form it's a robust way to estimate the standard deviation, for some kinds of data sets. Not used very often, but it does get reported sometimes.
--></li>
</ul>
<p>In short, the IQR and the standard deviation are easily the two most common measures used to report the variability of the data; but there are situations in which the others are used. I’ve described all of them in this book because there’s a fair chance you’ll run into most of these somewhere.</p>

</div>
</div>
</div>








<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>The choice to use <span class="math inline">\(\Sigma\)</span> to denote summation isn’t arbitrary: it’s the Greek upper case letter sigma, which is the analogue of the letter S in that alphabet. Similarly, there’s an equivalent symbol used to denote the multiplication of lots of numbers: because multiplications are also called “products”, we use the <span class="math inline">\(\Pi\)</span> symbol for this; the Greek upper case pi, which is the analogue of the letter P.<a href="descriptives.html#fnref1" class="footnote-back">↩</a></p></li>
<li id="fn2"><p>Or at least, the basic statistical theory – these days there is a whole subfield of statistics called <em>robust statistics</em> that tries to grapple with the messiness of real data and develop theory that can cope with it.<a href="descriptives.html#fnref2" class="footnote-back">↩</a></p></li>
<li id="fn3"><p>Well, I will very briefly mention the one that I think is coolest, for a very particular definition of “cool”, that is. Variances are <em>additive</em>. Here’s what that means: suppose I have two variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, whose variances are $<a href="descriptives.html#fnref3" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="scalesOfMeasurement.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["LectureNotes.pdf", "LectureNotes.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
